"""SQLAlchemy metadata for the four isolated Stage 16 tables."""
import sqlalchemy as sa
from database.models import Base

metadata=Base.metadata
high_impact_events=sa.Table("high_impact_events",metadata,
 sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("source",sa.String(100),nullable=False),sa.Column("source_type",sa.String(30),nullable=False),sa.Column("platform",sa.String(30),nullable=False),sa.Column("author_name",sa.String(255)),sa.Column("author_handle",sa.String(255)),sa.Column("external_id",sa.String(255)),sa.Column("url",sa.Text,nullable=False),sa.Column("canonical_url",sa.Text),sa.Column("title",sa.Text),sa.Column("body",sa.Text,nullable=False),sa.Column("published_at",sa.DateTime(timezone=True),nullable=False),sa.Column("modified_at",sa.DateTime(timezone=True)),sa.Column("discovered_at",sa.DateTime(timezone=True),nullable=False),sa.Column("deleted_at",sa.DateTime(timezone=True)),sa.Column("time_source",sa.String(50),nullable=False),sa.Column("time_confidence",sa.Numeric(5,4),nullable=False),sa.Column("source_authenticity",sa.Numeric(5,4),nullable=False),sa.Column("crypto_relevance",sa.Numeric(5,4),nullable=False),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("event_group_id",sa.String(64)),sa.Column("raw_metadata_json",sa.JSON,nullable=False,server_default=sa.text("'{}'")),sa.Column("status",sa.String(30),nullable=False),sa.Column("rejection_reason",sa.Text),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),
 sa.UniqueConstraint("url",name="uq_high_impact_events_url"),sa.UniqueConstraint("content_hash",name="uq_high_impact_events_content_hash"),sa.Index("uq_high_impact_platform_external_not_null","platform","external_id",unique=True,postgresql_where=sa.text("external_id IS NOT NULL")),sa.Index("uq_high_impact_canonical_not_null","canonical_url",unique=True,postgresql_where=sa.text("canonical_url IS NOT NULL")),sa.Index("ix_high_impact_published","published_at"),sa.Index("ix_high_impact_source","source"),sa.Index("ix_high_impact_author_handle","author_handle"),sa.Index("ix_high_impact_event_group","event_group_id"),sa.Index("ix_high_impact_relevance","crypto_relevance"),sa.Index("ix_high_impact_status","status"))

high_impact_event_assets=sa.Table("high_impact_event_assets",metadata,
 sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("event_id",sa.BigInteger,sa.ForeignKey("high_impact_events.id",ondelete="CASCADE"),nullable=False),sa.Column("asset",sa.String(10),nullable=False),sa.Column("relevance",sa.Numeric(5,4),nullable=False),sa.Column("detection_source",sa.String(50),nullable=False),sa.UniqueConstraint("event_id","asset",name="uq_high_impact_event_asset"),sa.CheckConstraint("asset IN ('BTC','ETH','SOL')",name="ck_high_impact_asset"),sa.Index("ix_high_impact_asset","asset"))

high_impact_event_analysis=sa.Table("high_impact_event_analysis",metadata,
 sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("event_id",sa.BigInteger,sa.ForeignKey("high_impact_events.id",ondelete="CASCADE"),nullable=False),sa.Column("model_name",sa.String(100),nullable=False),sa.Column("prompt_version",sa.String(50),nullable=False),sa.Column("event_type",sa.String(50)),sa.Column("information_status",sa.String(50)),
 *[sa.Column(x,sa.Integer) for x in ("source_reliability","novelty","importance","specificity","confidence","surprise_level","actionability","institutional_relevance","retail_relevance","regulatory_strength","economic_significance","technical_significance","security_significance","adoption_significance","execution_certainty","urgency","fundamental_relevance")],
 *[sa.Column(x,sa.String(50)) for x in ("surprise_evidence","first_disclosure","market_scope","temporary_vs_structural","evidence_quality")],
 sa.Column("assets_json",sa.JSON),sa.Column("input_hash",sa.String(64)),sa.Column("input_tokens",sa.Integer),sa.Column("output_tokens",sa.Integer),sa.Column("total_tokens",sa.Integer),sa.Column("estimated_cost_usd",sa.Numeric(14,8)),sa.Column("actual_cost_usd",sa.Numeric(14,8)),sa.Column("raw_response_json",sa.JSON),sa.Column("status",sa.String(30),nullable=False),sa.Column("error_message",sa.Text),sa.Column("analyzed_at",sa.DateTime(timezone=True)),sa.Column("batch_id",sa.String(100)),sa.Column("batch_custom_id",sa.String(150)),
 sa.UniqueConstraint("event_id","model_name","prompt_version",name="uq_high_impact_analysis_identity"),sa.Index("ix_high_impact_analysis_status","status"),sa.Index("ix_high_impact_analysis_batch_id","batch_id"),sa.Index("uq_high_impact_analysis_batch_custom_id","batch_custom_id",unique=True,postgresql_where=sa.text("batch_custom_id IS NOT NULL")))

reaction_columns=[sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("event_id",sa.BigInteger,sa.ForeignKey("high_impact_events.id",ondelete="CASCADE"),nullable=False),sa.Column("symbol",sa.String(20),nullable=False),sa.Column("baseline_time",sa.DateTime(timezone=True),nullable=False),sa.Column("latency_minutes",sa.Integer,nullable=False),sa.Column("baseline_price",sa.Numeric(30,12),nullable=False)]
reaction_columns += [sa.Column(f"return_{h}",sa.Numeric(18,8)) for h in ("1m","5m","10m","20m","40m","1h","3h","5h","8h","12h")]
reaction_columns += [sa.Column(f"abnormal_return_{h}",sa.Numeric(18,8)) for h in ("1m","5m","10m","20m","40m","1h","3h","5h","8h","12h")]
reaction_columns += [sa.Column(x,sa.Numeric(18,8)) for x in ("max_favorable_1h","max_adverse_1h","max_absolute_1h","max_favorable_12h","max_adverse_12h","max_absolute_12h","volume_shock_1h","realized_vol_1h","realized_vol_12h")]
reaction_columns += [sa.Column("pre_context_json",sa.JSON,nullable=False,server_default=sa.text("'{}'")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("event_id","symbol","latency_minutes",name="uq_high_impact_reaction_identity"),sa.Index("ix_high_impact_reaction_baseline","baseline_time")]
high_impact_market_reactions=sa.Table("high_impact_market_reactions",metadata,*reaction_columns)
