-- Crypto Market Reaction Database: website MVP table.
-- Apply with psql and ON_ERROR_STOP before running the importer.

BEGIN;

CREATE TABLE IF NOT EXISTS public.events (
    event_id text PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    title text NOT NULL CHECK (btrim(title) <> ''),
    published_at timestamptz NOT NULL,
    source text NOT NULL CHECK (btrim(source) <> ''),
    source_url text NOT NULL CHECK (btrim(source_url) <> ''),
    primary_asset text NULL CHECK (primary_asset IS NULL OR primary_asset IN ('BTC', 'ETH', 'SOL')),
    related_assets text[] NOT NULL CHECK (
        related_assets <@ ARRAY['BTC', 'ETH', 'SOL']::text[]
    ),
    category text NOT NULL,
    sentiment text NULL,
    sentiment_score double precision NULL,
    importance double precision NULL,
    ai_schema_version text NOT NULL,
    ai_prompt_version text NULL,
    ai_original_scale text NOT NULL,
    archive_dataset_source text NOT NULL CHECK (archive_dataset_source IN ('A', 'B', 'C')),
    archive_member_id text NOT NULL,
    reaction_methodology text NOT NULL,
    reaction_value_unit text NOT NULL CHECK (reaction_value_unit = 'percent'),

    btc_1m double precision NULL,
    btc_5m double precision NULL,
    btc_15m double precision NULL,
    btc_1h double precision NULL,
    btc_4h double precision NULL,
    btc_24h double precision NULL,
    btc_reaction_source text NULL,
    btc_reference_time timestamptz NULL,
    btc_reference_latency_minutes integer NULL CHECK (btc_reference_latency_minutes >= 0),

    eth_1m double precision NULL,
    eth_5m double precision NULL,
    eth_15m double precision NULL,
    eth_1h double precision NULL,
    eth_4h double precision NULL,
    eth_24h double precision NULL,
    eth_reaction_source text NULL,
    eth_reference_time timestamptz NULL,
    eth_reference_latency_minutes integer NULL CHECK (eth_reference_latency_minutes >= 0),

    sol_1m double precision NULL,
    sol_5m double precision NULL,
    sol_15m double precision NULL,
    sol_1h double precision NULL,
    sol_4h double precision NULL,
    sol_24h double precision NULL,
    sol_reaction_source text NULL,
    sol_reference_time timestamptz NULL,
    sol_reference_latency_minutes integer NULL CHECK (sol_reference_latency_minutes >= 0),

    search_vector tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english'::regconfig, coalesce(title, '')), 'A')
        || setweight(to_tsvector('simple'::regconfig, coalesce(source, '')), 'B')
        || setweight(to_tsvector('english'::regconfig, coalesce(category, '')), 'B')
    ) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- event_id and slug already receive unique B-tree indexes from their constraints.
CREATE INDEX IF NOT EXISTS ix_events_published_at
    ON public.events (published_at DESC);
CREATE INDEX IF NOT EXISTS ix_events_source
    ON public.events (source);
CREATE INDEX IF NOT EXISTS ix_events_primary_asset
    ON public.events (primary_asset)
    WHERE primary_asset IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_events_category
    ON public.events (category);
CREATE INDEX IF NOT EXISTS ix_events_related_assets_gin
    ON public.events USING gin (related_assets);
CREATE INDEX IF NOT EXISTS ix_events_search_vector_gin
    ON public.events USING gin (search_vector);

COMMENT ON TABLE public.events IS
    'One canonical historical crypto event per row for the website MVP.';
COMMENT ON COLUMN public.events.event_id IS
    'Stable canonical event identifier from events_mvp; never regenerated by PostgreSQL.';
COMMENT ON COLUMN public.events.related_assets IS
    'Validated subset of BTC, ETH and SOL converted from the dataset JSON array string.';
COMMENT ON COLUMN public.events.reaction_value_unit IS
    'All reaction values are percentage returns, not decimal fractions.';
COMMENT ON COLUMN public.events.search_vector IS
    'Generated weighted full-text document: title weight A; source/category weight B.';

COMMIT;
