"""SQLAlchemy metadata for isolated Stage 13.5 tables."""
import sqlalchemy as sa
from database.models import Base

metadata=Base.metadata
early_columns=[sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("news_id",sa.BigInteger,nullable=False),sa.Column("symbol",sa.String(20),nullable=False),sa.Column("baseline_time",sa.DateTime(timezone=True),nullable=False),sa.Column("latency_minutes",sa.Integer,nullable=False)]
early_columns += [sa.Column(f"return_{h}m",sa.Numeric(16,8)) for h in (1,2,3,5,10,15)]
early_columns += [sa.Column(f"abnormal_return_{h}m",sa.Numeric(16,8)) for h in (1,2,3,5,10,15)]
early_columns += [sa.Column(f"pre_return_{h}m",sa.Numeric(16,8)) for h in (1,2,3,5,10,15)]
early_columns += [sa.Column(f"btc_return_{h}m",sa.Numeric(16,8)) for h in (1,2,3,5,10,15)]
early_columns += [sa.Column(f"eth_minus_btc_{h}m",sa.Numeric(16,8)) for h in (1,2,3,5,10,15)]
early_columns += [sa.Column("max_favorable_5m",sa.Numeric(16,8)),sa.Column("max_adverse_5m",sa.Numeric(16,8)),sa.Column("max_absolute_5m",sa.Numeric(16,8)),sa.Column("realized_vol_5m",sa.Numeric(16,8)),sa.Column("volume_shock_5m",sa.Numeric(16,8)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("news_id","symbol","latency_minutes",name="uq_early_reaction_news_symbol_latency"),sa.Index("ix_early_reaction_baseline","baseline_time")]
for h in (1,3,5,10,15):
    if h!=5:early_columns += [sa.Column(f"max_favorable_{h}m",sa.Numeric(16,8)),sa.Column(f"max_adverse_{h}m",sa.Numeric(16,8)),sa.Column(f"max_absolute_{h}m",sa.Numeric(16,8)),sa.Column(f"realized_vol_{h}m",sa.Numeric(16,8)),sa.Column(f"volume_shock_{h}m",sa.Numeric(16,8))]
    early_columns += [sa.Column(f"high_low_range_{h}m",sa.Numeric(16,8)),sa.Column(f"time_to_max_move_{h}m",sa.Integer())]
news_early_reactions=sa.Table("news_early_reactions",metadata,*early_columns)

primary_source_events=sa.Table("primary_source_events",metadata,
 sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("source",sa.String(100),nullable=False),sa.Column("source_type",sa.String(30),nullable=False),sa.Column("url",sa.Text,nullable=False),sa.Column("canonical_url",sa.Text),
 sa.Column("title",sa.Text,nullable=False),sa.Column("body",sa.Text,nullable=False),sa.Column("published_at",sa.DateTime(timezone=True),nullable=False),sa.Column("modified_at",sa.DateTime(timezone=True)),sa.Column("discovered_at",sa.DateTime(timezone=True),nullable=False),
 sa.Column("time_source",sa.String(50),nullable=False),sa.Column("time_confidence",sa.Numeric(4,3),nullable=False),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("event_group_id",sa.String(64)),sa.Column("assets_json",sa.Text,server_default='["ETH"]',nullable=False),sa.Column("is_valid",sa.Boolean,server_default=sa.true(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),
 sa.UniqueConstraint("url",name="uq_primary_source_url"),sa.UniqueConstraint("content_hash",name="uq_primary_source_content_hash"),sa.Index("ix_primary_source_published","published_at"),sa.Index("ix_primary_source_event_group","event_group_id"),sa.Index("uq_primary_source_canonical_not_null","canonical_url",unique=True,postgresql_where=sa.text("canonical_url IS NOT NULL")))

event_information_timeline=sa.Table("event_information_timeline",metadata,
 sa.Column("event_key",sa.String(100),primary_key=True),sa.Column("earliest_primary_news_id",sa.BigInteger),sa.Column("earliest_media_news_id",sa.BigInteger,nullable=False),sa.Column("earliest_information_time",sa.DateTime(timezone=True),nullable=False),sa.Column("primary_source_time",sa.DateTime(timezone=True)),sa.Column("media_source_time",sa.DateTime(timezone=True),nullable=False),sa.Column("delay_seconds",sa.Integer),sa.Column("source_count",sa.Integer,nullable=False),sa.Column("article_count",sa.Integer,nullable=False),sa.Column("grouping_method",sa.String(50),nullable=False),sa.Column("grouping_confidence",sa.Numeric(5,4),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))

futures_funding_rates=sa.Table("futures_funding_rates",metadata,sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("symbol",sa.String(20),nullable=False),sa.Column("funding_time",sa.DateTime(timezone=True),nullable=False),sa.Column("funding_rate",sa.Numeric(20,12),nullable=False),sa.Column("mark_price",sa.Numeric(30,12)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("symbol","funding_time",name="uq_funding_symbol_time"),sa.Index("ix_futures_funding_rates_symbol_time","symbol","funding_time"))
futures_open_interest=sa.Table("futures_open_interest",metadata,sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("symbol",sa.String(20),nullable=False),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("open_interest",sa.Numeric(30,12),nullable=False),sa.Column("open_interest_value",sa.Numeric(30,8)),sa.Column("period",sa.String(10),nullable=False),sa.UniqueConstraint("symbol","timestamp","period",name="uq_oi_symbol_time_period"),sa.Index("ix_futures_open_interest_symbol_time","symbol","timestamp"))
futures_long_short_ratios=sa.Table("futures_long_short_ratios",metadata,sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("symbol",sa.String(20),nullable=False),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("ratio_type",sa.String(30),nullable=False),sa.Column("long_account",sa.Numeric(20,12)),sa.Column("short_account",sa.Numeric(20,12)),sa.Column("long_short_ratio",sa.Numeric(20,12),nullable=False),sa.Column("period",sa.String(10),nullable=False),sa.UniqueConstraint("symbol","timestamp","ratio_type","period",name="uq_ls_symbol_time_type_period"),sa.Index("ix_futures_long_short_ratios_symbol_time","symbol","timestamp"))
futures_taker_volume=sa.Table("futures_taker_volume",metadata,sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("symbol",sa.String(20),nullable=False),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("buy_sell_ratio",sa.Numeric(20,12),nullable=False),sa.Column("buy_volume",sa.Numeric(30,12)),sa.Column("sell_volume",sa.Numeric(30,12)),sa.Column("period",sa.String(10),nullable=False),sa.UniqueConstraint("symbol","timestamp","period",name="uq_taker_symbol_time_period"),sa.Index("ix_futures_taker_volume_symbol_time","symbol","timestamp"))
